export const ADD_ANIMAL_SUCCESS = 'ADD_ANIMAL_SUCCESS';
export const ADD_ANIMAL_STARTED = 'ADD_ANIMAL_STARTED';
export const ADD_ANIMAL_FAILURE = 'ADD_ANIMAL_FAILURE';

export const DELETE_ANIMAL_SUCCESS = 'DELETE_ANIMAL_SUCCESS';
export const DELETE_ANIMAL_STARTED = 'DELETE_ANIMAL_STARTED';
export const DELETE_ANIMAL_FAILURE = 'DELETE_ANIMAL_FAILURE';

export const CHANGE_ANIMAL_SUCCESS = 'CHANGE_ANIMAL_SUCCESS';
export const CHANGE_ANIMAL_STARTED = 'CHANGE_ANIMAL_STARTED';
export const CHANGE_ANIMAL_FAILURE = 'CHANGE_ANIMAL_FAILURE';

export const LOAD_ANIMAL_SUCCESS = 'LOAD_ANIMAL_SUCCESS';
export const LOAD_ANIMAL_STARTED = 'LOAD_ANIMAL_STARTED';
export const LOAD_ANIMAL_FAILURE = 'LOAD_ANIMAL_FAILURE';

export const SET_ANIMAL_PAGE_COUNT = 'SET_ANIMAL_PAGE_COUNT';

export const SET_ANIMAL_OPTIONS = 'SET_ANIMAL_OPTIONS';

export const SET_ANIMAL_CHECKED = 'SET_ANIMAL_CHECKED';
