export const ADD_PEOPLE_SUCCESS = 'ADD_PEOPLE_SUCCESS';
export const ADD_PEOPLE_STARTED = 'ADD_PEOPLE_STARTED';
export const ADD_PEOPLE_FAILURE = 'ADD_PEOPLE_FAILURE';

export const DELETE_PEOPLE_SUCCESS = 'DELETE_PEOPLE_SUCCESS';
export const DELETE_PEOPLE_STARTED = 'DELETE_PEOPLE_STARTED';
export const DELETE_PEOPLE_FAILURE = 'DELETE_PEOPLE_FAILURE';

export const CHANGE_PEOPLE_SUCCESS = 'CHANGE_PEOPLE_SUCCESS';
export const CHANGE_PEOPLE_STARTED = 'CHANGE_PEOPLE_STARTED';
export const CHANGE_PEOPLE_FAILURE = 'CHANGE_PEOPLE_FAILURE';

export const LOAD_PEOPLE_SUCCESS = 'LOAD_PEOPLE_SUCCESS';
export const LOAD_PEOPLE_STARTED = 'LOAD_PEOPLE_STARTED';
export const LOAD_PEOPLE_FAILURE = 'LOAD_PEOPLE_FAILURE';

export const SET_PEOPLE_PAGE_COUNT = 'SET_PEOPLE_PAGE_COUNT';

export const SET_PEOPLE_OPTIONS = 'SET_PEOPLE_OPTIONS';

export const SET_PEOPLE_CHECKED = 'SET_PEOPLE_CHECKED';
